# Generated by Django 5.2.9 on 2025-12-04 09:11

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Optional. Not used for login.', max_length=150, null=True, unique=True)),
                ('email', models.EmailField(help_text='Required. Used as username for login.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Basic Starter', 'Minimal Budget')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this template will be used for new households by default')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Template',
                'verbose_name_plural': 'Budget Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SAVINGS', 'Savings & Investments')], default='EXPENSE', max_length=7)),
                ('is_persistent', models.BooleanField(default=False, help_text='If checked, the budget amount will be carried over to the next month.')),
                ('payment_type', models.CharField(choices=[('AUTO', 'Automatic - No tracking needed'), ('MANUAL', 'Manual - Track payment'), ('INCOME', 'Income - No tracking needed')], default='MANUAL', help_text='How this category is paid/received.', max_length=10)),
                ('is_essential', models.BooleanField(default=True, help_text='For Barebones template: True = essential (keep amount), False = non-essential (zero out). Default is Essential for safety.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this budget item has been paid/received.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='finance.category')),
            ],
            options={
                'verbose_name': 'Category Note',
                'verbose_name_plural': 'Category Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Household name (e.g., 'Smith Family')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(help_text="Users who have access to this household's budget", related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(help_text='Household this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.household'),
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SAVINGS', 'Savings & Investments')], default='EXPENSE', max_length=7)),
                ('is_persistent', models.BooleanField(default=False, help_text='If checked, the budget amount will be carried over to the next month.')),
                ('payment_type', models.CharField(choices=[('AUTO', 'Automatic - No tracking needed'), ('MANUAL', 'Manual - Track payment'), ('INCOME', 'Income - No tracking needed')], default='MANUAL', help_text='How this category is paid/received.', max_length=10)),
                ('is_essential', models.BooleanField(default=True, help_text='For Barebones template: True = essential (keep amount), False = non-essential (zero out).')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories should be displayed')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (for sub-categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.templatecategory')),
                ('template', models.ForeignKey(help_text='Template this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.budgettemplate')),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('household', models.ForeignKey(help_text='Household this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecategory',
            unique_together={('template', 'name', 'parent')},
        ),
    ]
