# Generated by Django 5.2.8 on 2025-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_persistent',
            field=models.BooleanField(default=False, help_text='If checked, the budget amount will be carried over to the next month.'),
        ),
    ]
