# Generated by Django 5.2.8 on 2025-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_is_persistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this budget item has been paid/received.'),
        ),
        migrations.AddField(
            model_name='category',
            name='payment_type',
            field=models.CharField(choices=[('AUTO', 'Automatic - No tracking needed'), ('MANUAL', 'Manual - Track payment'), ('INCOME', 'Income - No tracking needed')], default='MANUAL', help_text='How this category is paid/received.', max_length=10),
        ),
    ]
