# Generated by Django 5.2.8 on 2025-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budget_is_paid_category_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SAVINGS', 'Savings & Investments')], default='EXPENSE', max_length=7),
        ),
    ]
