# Generated by Django 5.2.8 on 2025-12-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_household_and_assign_data(apps, schema_editor):
    """Create a default household and assign all existing categories/transactions to it"""
    Household = apps.get_model('finance', 'Household')
    Category = apps.get_model('finance', 'Category')
    Transaction = apps.get_model('finance', 'Transaction')
    User = apps.get_model('auth', 'User')
    
    # Create default household
    default_household = Household.objects.create(name='Default Household')
    
    # Get or create a default user (skip password setting in migration)
    default_user, user_created = User.objects.get_or_create(
        username='default_user',
        defaults={
            'email': 'default@example.com',
            'first_name': 'Default',
            'last_name': 'User'
        }
    )
    
    # Add user to household
    default_household.members.add(default_user)
    
    # Assign all categories without household to default household
    Category.objects.filter(household__isnull=True).update(household=default_household)
    
    # Assign all transactions without household to default household
    Transaction.objects.filter(household__isnull=True).update(household=default_household)


def reverse_migration(apps, schema_editor):
    """Reverse migration - set household to null"""
    Category = apps.get_model('finance', 'Category')
    Transaction = apps.get_model('finance', 'Transaction')
    
    Category.objects.all().update(household=None)
    Transaction.objects.all().update(household=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Household name (e.g., 'Smith Family')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(help_text="Users who have access to this household's budget", related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Household this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.household'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Household this transaction belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household'),
        ),
        migrations.RunPython(create_default_household_and_assign_data, reverse_migration),
    ]
