# Generated by Django 5.2.8 on 2025-12-02 10:29

import django.db.models.deletion
from django.db import migrations, models


def ensure_all_have_household(apps, schema_editor):
    """Ensure all categories and transactions have a household assigned"""
    Household = apps.get_model('finance', 'Household')
    Category = apps.get_model('finance', 'Category')
    Transaction = apps.get_model('finance', 'Transaction')
    
    # Get the default household (should exist from previous migration)
    default_household = Household.objects.first()
    
    if default_household:
        # Assign any remaining null values to default household
        Category.objects.filter(household__isnull=True).update(household=default_household)
        Transaction.objects.filter(household__isnull=True).update(household=default_household)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_household_category_household_transaction_household'),
    ]

    operations = [
        migrations.RunPython(ensure_all_have_household, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='household',
            field=models.ForeignKey(help_text='Household this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.household'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(help_text='Household this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household'),
        ),
    ]
