# Generated by Django 5.2.8 on 2025-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_make_household_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_essential',
            field=models.BooleanField(blank=True, help_text='For Barebones template: True = essential (keep amount), False = non-essential (zero out). Leave blank for auto-detection based on category name.', null=True),
        ),
    ]
