# Generated by Django 5.2.8 on 2025-12-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_category_is_essential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_essential',
            field=models.BooleanField(default=True, help_text='For Barebones template: True = essential (keep amount), False = non-essential (zero out). Default is Essential for safety.'),
        ),
    ]
