# Generated by Django 5.2.8 on 2025-12-02 11:28

from django.db import migrations


def set_all_categories_to_essential(apps, schema_editor):
    """Set all existing categories to Essential (True) for safety"""
    Category = apps.get_model('finance', 'Category')
    # Update all categories to Essential (True)
    Category.objects.all().update(is_essential=True)


def reverse_migration(apps, schema_editor):
    """Reverse migration - not really needed but for completeness"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_category_is_essential'),
    ]

    operations = [
        migrations.RunPython(set_all_categories_to_essential, reverse_migration),
    ]
