# Generated by Django 5.2.8 on 2025-12-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_set_existing_categories_to_essential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='finance.category')),
            ],
            options={
                'verbose_name': 'Category Note',
                'verbose_name_plural': 'Category Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
