# Generated by Django 5.2.8 on 2025-12-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_categorynote'),
        ('finance', '0014_user'),  # Explicitly depend on User model creation
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Basic Starter', 'Minimal Budget')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template includes')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this template will be used for new households by default')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Template',
                'verbose_name_plural': 'Budget Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SAVINGS', 'Savings & Investments')], default='EXPENSE', max_length=7)),
                ('is_persistent', models.BooleanField(default=False, help_text='If checked, the budget amount will be carried over to the next month.')),
                ('payment_type', models.CharField(choices=[('AUTO', 'Automatic - No tracking needed'), ('MANUAL', 'Manual - Track payment'), ('INCOME', 'Income - No tracking needed')], default='MANUAL', help_text='How this category is paid/received.', max_length=10)),
                ('is_essential', models.BooleanField(default=True, help_text='For Barebones template: True = essential (keep amount), False = non-essential (zero out).')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories should be displayed')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (for sub-categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.templatecategory')),
                ('template', models.ForeignKey(help_text='Template this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.budgettemplate')),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('template', 'name', 'parent')},
            },
        ),
    ]
